### PR TITLE
Design docs

### PR DESCRIPTION
**Pull request by jecarr**

### CODE REVIEW

**Comment by jecarr** [comment]
Thanks @cvallance for your work on #91 so far! As discussed, this PR has some write-up on what the different parts of Thread look like. I hope it helps and as you're getting familiar with the codebase, please let us know if you spot how else we can improve docs/what's missing from here.

@KadeMorton, please also let me know if you spot anything I've missed too?

Thanks!

**Comment by cvallance** [comment]
This is great thanks!

One suggestion would be to put more documentation closer to the source, e.g. copy/move detail about the classes from the `DESIGN.md` file into the actual python docs. Reason being is that this is more discoverable for developers when they are going about their work... many modern IDEs and developer tooling can also use these code comments to surface them in many helpful places, e.g. intellisense.

There's also a bunch of developer AI tooling (e.g. copilot) can take the code docs to make better informed code suggestions and the likes.

**Comment by jecarr** [comment]
Thanks for the feedback! I'll add to this branch to move the details closer to the source as suggested

**Comment by jecarr** [comment]
Closing as the branch is stale (sorry, I haven't been updating this one)

**Pull request closed without merging**
